services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: internal
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "3333:3333"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=internal
      - DB_SSLMODE=disable
    depends_on:
      - db